Add most populars
evilaks/java-filmorate pull request #14
Opened 2023-03-04 10:48 UTC by mao2201100

2023-03-05 19:47 UTC, evilaks commented
Надо целевую ветку поменять с main на develop

2023-03-06 07:48 UTC, evilaks submitted a review, later dismissed
Нечего добавить, всё ок)

2023-03-06 08:05 UTC, zykininho approved these changes
Все отлично

2023-03-06 08:10 UTC, evilaks requested changes

2023-03-06 08:10 UTC, evilaks commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    public List<Long> getPopularFilmGenreIdYear(int year, int genreId, int count) {
Нужно чуть поправить оформление, пробелы расставить в else if. Это повышает читаемость кода. Мы теперь работаем командой, поэтому за такими вещами тоже лучше следить)

2023-03-06 08:10 UTC, evilaks commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> mutualFilmList = new ArrayList<>();
Тут название переменной надо поправить. В этом запросе нет общих фильмов

2023-03-06 08:10 UTC, evilaks commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getPopularFilmGenreIdYear(int count, int genreId, int year){
Тут, кажется, не хватает валидации. Что будет, если приедет genreId со значением -1? Или год 1700?

2023-03-06 14:58 UTC, mao2201100 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    public List<Long> getPopularFilmGenreIdYear(int year, int genreId, int count) {
Готово

2023-03-06 15:02 UTC, mao2201100 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> mutualFilmList = new ArrayList<>();
Готово

2023-03-06 18:31 UTC, mao2201100 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getPopularFilmGenreIdYear(int count, int genreId, int year){
Добавил

2023-03-06 18:38 UTC, evilaks approved these changes
Всё отлично)

2023-03-06 18:38 UTC, evilaks commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    public List<Long> getPopularFilmGenreIdYear(int year, int genreId, int count) {
Супер!

2023-03-06 18:47 UTC, merged